# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

# More info on config here:
## https://github.com/golangci/golangci-lint#config-file
## https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    # report about not checking of errors in type assetions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: true

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: true
  govet:
    enable-all: true
  revive: # golint was replaced by revive
    rules:
      # Recommended in Revive docs
      # https://github.com/mgechev/revive#recommended-configuration
      - name: package-comments
        disabled: true
      - name: exported
        arguments:
          - disableStutteringCheck
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    # best practices: between 10 and 20, depending on the application domain
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - revive # 'golint' is deprecated (since v1.41.0), replaced by revive
    - govet
    - errcheck
    - ineffassign
    - typecheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - staticcheck
    - unused
    - depguard
    - unconvert
    - unparam
    - unused
    - nakedret
    ## too many false positives
    # - dupl

issues:
  exclude-dirs:
    - .git
    - bin
    - vendor
    - node_modules
    - var
    - gen.*
    - tmp
  exclude-files:
    - \.pb\.go$
    - \.pb\.goclay\.go$

  exclude-use-default: false
  exclude:
    - fieldalignment ## this is important, but too many occurrences in the codebase
    - is not allowed from list 'Main'
