---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: lfx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: app
          image: linuxfoundation/demo-indexer:0.3.1
          imagePullPolicy: Never
          env:
            - name: OPENSEARCH_URL
              value: "http://opensearch-cluster-master:9200"
          ports:
            - containerPort: 8080
              name: web
          livenessProbe:
            httpGet:
              path: /livez
              port: web
            failureThreshold: 3
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: web
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /readyz
              port: web
            failureThreshold: 30
            periodSeconds: 1
