# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{- if .Values.nats.stream_index_events.creation }}
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: {{ .Values.nats.stream_index_events.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nats.stream_index_events.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  name: {{ .Values.nats.stream_index_events.name }}
  subjects:
    {{- toYaml .Values.nats.stream_index_events.subjects | nindent 4 }}
  retention: {{ .Values.nats.stream_index_events.retention }}
  maxAge: {{ .Values.nats.stream_index_events.maxAge }}
  maxBytes: {{ .Values.nats.stream_index_events.maxBytes }}
  maxMsgs: {{ .Values.nats.stream_index_events.maxMsgs }}
  storage: {{ .Values.nats.stream_index_events.storage }}
  replicas: {{ .Values.nats.stream_index_events.replicas }}
  compression: {{ .Values.nats.stream_index_events.compression }}
{{- end }}
